### ISSUE TITLE
Misprint in Commentaries within README File

### ISSUE THREAD

**Issue by Qlalq** [jszheng21/RACE#1]
I have noticed an inconsistency in the Code Evaluation section of the README, where the following command sequence is presented:
```
# For `Readability`
scripts/eval_c_maintainability.sh ${model} ${root}

# For `Efficiency`
scripts/eval_c_efficiency.sh ${model} ${root}
```
I think the first comment should be corrected to:
```
# For `Maintainability`
```

**Comment by jszheng21** [comment]
Thank you for your careful observation; we have corrected the erroneous comment.
